### ISSUE TITLE
Allow for pipeline hints to contain html

### ISSUE THREAD

**Issue by gscho** [buildkite/site#562]
Hi All, not sure if this is the right spot to open an issue...

I'd like to have pipeline hints be able to contain HTML or just clickable links.

The use case is I want to link to some documentation in the hint for the pipeline user but it just renders as text in the pipeline window.

Example:

```
steps:
  - block: "Request Release"
    fields:
      - select: "Deploy type"
        key: "deploy-type"
        hint: "Select a deploy type. See https://mylink.com for details"
        options:
          - label: "Default"
            value: "default"
          - label: "Fast"
            value: "fast"
          - label: "Restart"
            value: "restart"
          - label: "Rollback"
            value: "rollback"
```

Would be cool if markdown or html tags were supported!
